
#!/bin/bash

# It is good practice to first run the app and then use these curl commands to test the APIs.

BASE_URL="http://localhost:5000"

# Endpoints
API_ENDPOINTS=(
    "/api/auth"
    "/api/users"
    "/api/categories"
    "/api/products"
    "/api/orders"
    "/api/escrows"
    "/api/transactions"
    "/api/drivers"
    "/api/merchants"
    "/api/fuel-orders"
    "/api/delivery-feedback"
    "/api/support-tickets"
    "/api/support-ticket-messages"
    "/api/audit-logs"
    "/api/tracking"
    "/api/fraud-alerts"
    "/api/messages"
    "/api/notifications"
    "/api/identity-verifications"
    "/api/error-logs"
    "/api/mfa-tokens"
    "/api/jwt-tokens"
    "/api/password-reset"
    "/api/verification-documents"
    "/api/security-logs"
    "/api/trusted-devices"
    "/api/toll-gates"
    "/api/suspicious-activities"
    "/api/admin-users"
    "/api/content-reports"
    "/api/moderation-responses"
    "/api/firebase"
    "/api/web"
    "/api/realtime"
    "/api/realtime-examples"
    "/api/push-notifications"
    "/api/analytics"
    "/api/admin-dashboard"
    "/api/config"
    "/api/health"
    "/api/driver-verification"
    "/api/delivery-assignments"
    "/api/search"
    "/api/upload"
    "/api/geolocation"
    "/api/webhooks"
    "/api/payments"
    "/api/cart"
    "/api/checkout"
    "/api/bank-accounts"
    "/api/paystack"
    "/api/driver/location"
    "/api/qr"
    "/api/orders/auto-assign"
    "/api/admin/reports"
    "/api/admin/system-metrics"
    "/api/escrow-status"
    "/api/driver"
    "/"
    "/health"
)

# Iterate over the endpoints and execute curl commands
for endpoint in "${API_ENDPOINTS[@]}"
do
    echo "Testing endpoint: $endpoint"
    curl -X GET "$BASE_URL$endpoint"
    echo -e "\n"
done
